### ISSUE TITLE
Support for -M family of options

### ISSUE THREAD

**Issue by ilyapopov** [ThePhD/embed#1]
If I understand correctly, currently `std::embed` is not integrated with `-M` family of options. I wonder if that could be possible, such that the build system could learn about dependency on the embedded file.

**Comment by ThePhD** [comment]
`#embed` is supported with the -M options in both GCC and Clang right now.

`std::embed` cannot export dependency information right now, because it runs far after the `-M` style of options. `#embed` is at Phase 4 of the compiler, which is Preprocessing Time. `std::embed` is Phase 7, which is `constant evaluation` and regular C++ compile time.

We are looking into ways to make it easy to specify potential dependencies.

**Comment by ilyapopov** [comment]
Thanks for clarification!
